name: Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
    - run: "./scripts/showDeps.hs"
